spring:
  security:
    oauth2:
      client:
        registration: ## OAuth 로그인 시 설정한 Appliccation의 정보를 사용하여 accessToken을 Authorization Server에게 발급받을 떄 사용
          google:
            client-id: 761812531667-sr1001etoj40rrp5eh5hbiivdknbe5uq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email