spring:
  security:
    oauth2:
      client:
        registration: ## OAuth 로그인 시 설정한 Appliccation의 정보를 사용하여 accessToken을 Authorization Server에게 발급받을 떄 사용
          google:
            client-id: 17751618050-3hdpdk5l3rpvhe6mi1i31bp88g61qnkk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email