spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/dailymate?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
    defer-datasource-initialization: true