spring:
  profiles:
    include:
      - h2
#      - mariaDb
      - s3
      - jwt
      - swagger
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true